export default [
    "AI",
    "Blockchain",
    "Big Data",
    "Cloud",
    "Quantum Computing",
    "Internet of Things",
    "Cybersecurity",
    "Virtual Reality",
    "Video Games",
    "Metaverse",
    "Space",
    "Apple",
    "Biometrics",
    "Cars",
    "Elon Musk",
    "Facebook",
    "Cellular Networks",
    "Crypto",
    "Streaming",
]